### PR TITLE
More updates for the welding/grinding area section

### PR DESCRIPTION
**Pull request by diazwatson**
Does anyone know why the [Admonitions](https://squidfunk.github.io/mkdocs-material/reference/admonitions/) do not show correctly in https://docs.hacman.org.uk/Workshop_Areas/Welding/?

**Expected**
Screenshot 2024-01-26 at 15 24 24

**Actual** 
Screenshot 2024-01-26 at 15 24 34

### CODE REVIEW

**Comment by Hecatron** [comment]
It looks like someone has changed something that has broken it
some point after commit 4b7f1d0, currently trying to narrow it down

**Comment by Hecatron** [comment]
Looks like peter took it out here for some reason
https://github.com/HACManchester/documentation/commit/4d3255cfc14a8eb2b4d61b6c15b13e5da5e80d9d#diff-98d0f806abc9af24e6a7c545d3d77e8f9ad57643e27211d7a7b896113e420ed2

**Comment by Hecatron** [comment]
After speaking with peter it looks like he replaced the plugins with newer ones
so instead we're now using
```
pymdownx.blocks.admonition
pymdownx.blocks.details
```

different syntax
https://facelessuser.github.io/pymdown-extensions/extensions/blocks/plugins/admonition/

**Comment by diazwatson** [comment]
Cheers, I will update my PR

**Comment by diazwatson** [comment]
Done

**Pull request merged**
